### ISSUE TITLE
 -----END RSA PRIVATE KEY not found

### ISSUE THREAD

**Issue by tarun00197** [docusign/eg-01-csharp-jwt-framework#5]
I Updated the app.config file with  the RSA Private  Key generated the from the Portal. But got the below exception. Any ideas how to Fix.
```
System.IO.IOException: -----END RSA PRIVATE KEY not found
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.LoadObject(String type)
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.ReadPemObject()
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at DocuSign.eSign.Client.ApiClient.CreateRSAKeyFromPem(String key)
   at DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)
   at eg_01_csharp_jwt.ExampleBase.UpdateToken() in C:\Users\tarun.d\Downloads\eg-01-csharp-jwt-framework-master\eg-01-csharp-jwt-framework-master\common\ExampleBase.cs:line 42
   at eg_01_csharp_jwt.ExampleBase.CheckToken() in C:\Users\tarun.d\Downloads\eg-01-csharp-jwt-framework-master\eg-01-csharp-jwt-framework-master\common\ExampleBase.cs:line 36
   at eg_01_csharp_jwt.SendEnvelope.Send() in C:\Users\tarun.d\Downloads\eg-01-csharp-jwt-framework-master\eg-01-csharp-jwt-framework-master\common\SendEnvelope.cs:line 62
   at eg_01_csharp_jwt.Program.Main(String[] args) in C:\Users\tarun.d\Downloads\eg-01-csharp-jwt-framework-master\eg-01-csharp-jwt-framework-master\common\Program.cs:line 17
```

**Comment by mmallis87** [comment]
Make sure to include the whole RSA key text (include BEGIN and END lines). Also you need to encode newline characters ("&#xA;"). See the App.Config example for reference: https://github.com/docusign/eg-01-csharp-jwt-framework/blob/1fe99142df89bb8f1a4f43310a777d8eaa9f838b/common/App.config_example.txt#L12-L21

**Comment by tarun00197** [comment]
Thanks  for the Update.Its working fine now.
